// This header file was auto-generated by ClassMate++
// Created: 11 Oct 2015 5:21:41 pm
// Copyright (c) 2015, HurleyWorks

#pragma once

#include <cinder/Filesystem.h>
#include "../../../g3logger/g3logger.h"

typedef std::shared_ptr<class Log> LogRef;

class Log
{

 public:
	 Log(const std::string & logFolder, const std::string & appName);
	~Log ();
		
 private:
	std::string logFolder;
	g2::DefaultFileLogger logger;

	static void ReverseToOriginalFatalHandling();
	static void onFatalError(g2::FatalMessagePtr fatal_message);

}; // end class Log
